apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hashicorp-http-echo
  name: hashicorp-http-echo
spec:
  containers:
  - image: hashicorp/http-echo:latest
    name: hashicorp-http-echo
    args:
    - "-text=1.0.0"  
    ports:
    - containerPort: 5678
