apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
 containers:    
 - name: nginx      
   image: nginx      
   resources:        
     requests:          
       memory: "50Mi"
       cpu: "500m"        
     limits:          
       memory: "100Mi"
       cpu: 1

