stages:
  - test
  - build
  - deploy

variables:
  LOG_LEVEL: "DEBUG"

lint-test-job:
  image: ghcr.io/astral-sh/uv:0.9.24-python3.10-alpine
  stage: test
  script:
    - uv run ruff check

unit-test-job:
  image: ghcr.io/astral-sh/uv:0.9.24-python3.10-alpine
  stage: test
  before_script:
    - cd $CI_PROJECT_DIR
  script:
    - uv run pytest

build-job:
  stage: build
  image: quay.io/buildah/stable:latest
  variables:
    REGISTRY_HOST: "gitlab-schulung.oci.ordix.de"
    REGISTRY_PORT: "5050"
    REGISTRY_IMAGE_PATH: "user1/mein_fork"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin "$REGISTRY_HOST:$REGISTRY_PORT"
    - export APP_IMAGE="$REGISTRY_HOST:$REGISTRY_PORT/$REGISTRY_IMAGE_PATH:$CI_COMMIT_SHORT_SHA"
    - export APP_IMAGE_LATEST="$REGISTRY_HOST:$REGISTRY_PORT/$REGISTRY_IMAGE_PATH:latest"
  script:
    - buildah bud -t "$APP_IMAGE" -t "$APP_IMAGE_LATEST" .
    - buildah push "$APP_IMAGE"
    - buildah push "$APP_IMAGE_LATEST"

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Using log level $LOG_LEVEL"
    - echo "Deploying application..."
    - echo "Application successfully deployed."
