apiVersion: v1
kind: Service
metadata:
  name: todos
  #namespace: ngj
  labels:
    app.kubernetes.io/name: todos
    app.kubernetes.io/instance: todos
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Kubectl
    app.kubernetes.io/created-by: ngj
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: todos
    app.kubernetes.io/instance: todos
