apiVersion: v1
kind: Service
metadata:
  name: hashicorp-service-nodeport
spec:
  type: NodePort
  selector:
    app: hashicorp-echo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9999
     # optional nodePort: <Node-Port> festlegen
