apiVersion: v1
kind: Pod
metadata:
  name: mein-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: stay-healthy-for-30-seconds
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 10; rm -f /tmp/healthy; sleep 300
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy

