apiVersion: v1
kind: Pod
metadata:
  name: secretvolume-test-pod
spec:
  containers:
    - name: secretvolume-test-container
      image: busybox
      command: [ "/bin/sh", "-c", "ls -lL /secret/ && cat /secret/secret.properties ; echo '\nready'" ]
      volumeMounts:
        - name: test-secret-volume
          mountPath: /secret
  volumes:
    - name: test-secret-volume
      secret:
        secretName: secret-file
        defaultMode: 0400
  restartPolicy: Never

