apiVersion: v1
kind: Pod
metadata:
  name: app-logstash-pod
spec:
  containers:
    - name: application
      image: busybox
      command: ["sh", "-c", "while true; do echo $(date) Application log message >> /shared-logs/app.log; sleep 5; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared-logs
    - name: logstash
      image: busybox
      command: ["sh", "-c", "tail -f /shared-logs/app.log"]
      volumeMounts:
        - name: shared-data
          mountPath: /shared-logs
  volumes:
    - name: shared-data
      emptyDir: {} 
 
