apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: pv-www

  volumes:
    - name: pv-www
      persistentVolumeClaim:
        claimName: pvc-nginx-webdata
